meta_product_name: "DreamSharing"
meta_title: "DreamSharing - Sleep, Dream and Share it!"
meta_description: "Dreamsharing allows people to keep a dream journal online and share their dreams."
meta_image: "cover.png" # should exist in `app/assets/images/`
